/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"

int calcFactorial(int n)
{
    return (n==1 || n==0) ? 1: n * calcFactorial(n - 1);
}

int *
factorial_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

    result = calcFactorial(argp->a);
    printf("server: factorial of %d = %d\n", argp->a, result);


	return &result;
}
